name: build-windows-baremetal
on: push
jobs:
  build-windows:
    name: Build ModShot for Windows without Docker containers
    runs-on: windows-2019
    env:
      CONAN_USER_HOME: "${{ runner.temp }}\\conan"
      CONAN_USER_HOME_SHORT: "${{ runner.temp }}\\conan\\short"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and setup conan
        run: |
          mkdir ${{ runner.temp }}\conan;
          mkdir ${{ runner.temp }}\build;
          choco install -y conan vim;
          [Environment]::SetEnvironmentVariable('Path', $env:Path + ';C:\tools\vim\vim82', 'Machine');
          conan remote add eliza https://api.bintray.com/conan/eliza/conan;
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan;
          setx CONAN_USE_ALWAYS_SHORT_PATHS 1
      - name: Cache conan dependencies
        uses: actions/cache@v2
        with:
          path: env.CONAN_USER_HOME
          key: ${{ runner.os }}-cached-conan-modules-${{ hashFiles('conanfile.py') }}
      - name: Build dependencies using conan
        run: conan install ${{ github.workspace }} --build=missing
        working-directory: ${{ runner.temp }}\build
      - name: Build ModShot
        run: conan build ${{ github.workspace }}
        working-directory: ${{ runner.temp }}\build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: modshot_build_windows_latest
          path: ${{ runner.temp }}\build\bin
